(cl:in-package delta_amr_service-srv)
(cl:export '(IMG_PROCESS_TYPE_REALSENSE-VAL
          IMG_PROCESS_TYPE_REALSENSE
          IMG_PROCESS_TYPE_MECHMIND-VAL
          IMG_PROCESS_TYPE_MECHMIND
          ROBOT_MOV_TYPE-VAL
          ROBOT_MOV_TYPE
          ROBOT_MOV_POINT-VAL
          ROBOT_MOV_POINT
          ROBOT_MOV_SPEED-VAL
          ROBOT_MOV_SPEED
          HUMAN_DIST-VAL
          HUMAN_DIST
          ROBOT_RUNNING_STATUS-VAL
          ROBOT_RUNNING_STATUS
))