// Generated by gencpp from file delta_amr_service/delta_amr_service.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_DELTA_AMR_SERVICE_H
#define DELTA_AMR_SERVICE_MESSAGE_DELTA_AMR_SERVICE_H

#include <ros/service_traits.h>


#include <delta_amr_service/delta_amr_serviceRequest.h>
#include <delta_amr_service/delta_amr_serviceResponse.h>


namespace delta_amr_service
{

struct delta_amr_service
{

typedef delta_amr_serviceRequest Request;
typedef delta_amr_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct delta_amr_service
} // namespace delta_amr_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delta_amr_service::delta_amr_service > {
  static const char* value()
  {
    return "5f036b9efe5e6058b93abe4b32fb58c0";
  }

  static const char* value(const ::delta_amr_service::delta_amr_service&) { return value(); }
};

template<>
struct DataType< ::delta_amr_service::delta_amr_service > {
  static const char* value()
  {
    return "delta_amr_service/delta_amr_service";
  }

  static const char* value(const ::delta_amr_service::delta_amr_service&) { return value(); }
};


// service_traits::MD5Sum< ::delta_amr_service::delta_amr_serviceRequest> should match
// service_traits::MD5Sum< ::delta_amr_service::delta_amr_service >
template<>
struct MD5Sum< ::delta_amr_service::delta_amr_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::delta_amr_service >::value();
  }
  static const char* value(const ::delta_amr_service::delta_amr_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::delta_amr_serviceRequest> should match
// service_traits::DataType< ::delta_amr_service::delta_amr_service >
template<>
struct DataType< ::delta_amr_service::delta_amr_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::delta_amr_service >::value();
  }
  static const char* value(const ::delta_amr_service::delta_amr_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delta_amr_service::delta_amr_serviceResponse> should match
// service_traits::MD5Sum< ::delta_amr_service::delta_amr_service >
template<>
struct MD5Sum< ::delta_amr_service::delta_amr_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::delta_amr_service >::value();
  }
  static const char* value(const ::delta_amr_service::delta_amr_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::delta_amr_serviceResponse> should match
// service_traits::DataType< ::delta_amr_service::delta_amr_service >
template<>
struct DataType< ::delta_amr_service::delta_amr_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::delta_amr_service >::value();
  }
  static const char* value(const ::delta_amr_service::delta_amr_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_DELTA_AMR_SERVICE_H
