// Generated by gencpp from file delta_amr_service/delta_amr_serviceRequest.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_DELTA_AMR_SERVICEREQUEST_H
#define DELTA_AMR_SERVICE_MESSAGE_DELTA_AMR_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_amr_service
{
template <class ContainerAllocator>
struct delta_amr_serviceRequest_
{
  typedef delta_amr_serviceRequest_<ContainerAllocator> Type;

  delta_amr_serviceRequest_()
    : img_process_type_realsense()
    , img_process_type_mechmind()
    , robot_mov_type()
    , robot_mov_point()
    , robot_mov_speed(0)  {
    }
  delta_amr_serviceRequest_(const ContainerAllocator& _alloc)
    : img_process_type_realsense(_alloc)
    , img_process_type_mechmind(_alloc)
    , robot_mov_type(_alloc)
    , robot_mov_point(_alloc)
    , robot_mov_speed(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _img_process_type_realsense_type;
  _img_process_type_realsense_type img_process_type_realsense;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _img_process_type_mechmind_type;
  _img_process_type_mechmind_type img_process_type_mechmind;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_mov_type_type;
  _robot_mov_type_type robot_mov_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_mov_point_type;
  _robot_mov_point_type robot_mov_point;

   typedef int32_t _robot_mov_speed_type;
  _robot_mov_speed_type robot_mov_speed;





  typedef boost::shared_ptr< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct delta_amr_serviceRequest_

typedef ::delta_amr_service::delta_amr_serviceRequest_<std::allocator<void> > delta_amr_serviceRequest;

typedef boost::shared_ptr< ::delta_amr_service::delta_amr_serviceRequest > delta_amr_serviceRequestPtr;
typedef boost::shared_ptr< ::delta_amr_service::delta_amr_serviceRequest const> delta_amr_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator1> & lhs, const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.img_process_type_realsense == rhs.img_process_type_realsense &&
    lhs.img_process_type_mechmind == rhs.img_process_type_mechmind &&
    lhs.robot_mov_type == rhs.robot_mov_type &&
    lhs.robot_mov_point == rhs.robot_mov_point &&
    lhs.robot_mov_speed == rhs.robot_mov_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator1> & lhs, const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_amr_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e8d5e0a421c9f98f64d5abd9fa2e5da";
  }

  static const char* value(const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e8d5e0a421c9f98ULL;
  static const uint64_t static_value2 = 0xf64d5abd9fa2e5daULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_amr_service/delta_amr_serviceRequest";
  }

  static const char* value(const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Delta_AMR_Service.srv\n"
"# Request\n"
"\n"
"string img_process_type_realsense \n"
"string img_process_type_mechmind \n"
"\n"
"string robot_mov_type \n"
"string robot_mov_point\n"
"int32 robot_mov_speed\n"
"\n"
;
  }

  static const char* value(const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img_process_type_realsense);
      stream.next(m.img_process_type_mechmind);
      stream.next(m.robot_mov_type);
      stream.next(m.robot_mov_point);
      stream.next(m.robot_mov_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct delta_amr_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_amr_service::delta_amr_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "img_process_type_realsense: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.img_process_type_realsense);
    s << indent << "img_process_type_mechmind: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.img_process_type_mechmind);
    s << indent << "robot_mov_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_mov_type);
    s << indent << "robot_mov_point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_mov_point);
    s << indent << "robot_mov_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_mov_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_DELTA_AMR_SERVICEREQUEST_H
