// Generated by gencpp from file delta_amr_service/mechmind_srvResponse.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_MECHMIND_SRVRESPONSE_H
#define DELTA_AMR_SERVICE_MESSAGE_MECHMIND_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_amr_service
{
template <class ContainerAllocator>
struct mechmind_srvResponse_
{
  typedef mechmind_srvResponse_<ContainerAllocator> Type;

  mechmind_srvResponse_()
    : camera_status(0)  {
    }
  mechmind_srvResponse_(const ContainerAllocator& _alloc)
    : camera_status(0)  {
  (void)_alloc;
    }



   typedef int32_t _camera_status_type;
  _camera_status_type camera_status;





  typedef boost::shared_ptr< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mechmind_srvResponse_

typedef ::delta_amr_service::mechmind_srvResponse_<std::allocator<void> > mechmind_srvResponse;

typedef boost::shared_ptr< ::delta_amr_service::mechmind_srvResponse > mechmind_srvResponsePtr;
typedef boost::shared_ptr< ::delta_amr_service::mechmind_srvResponse const> mechmind_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator1> & lhs, const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.camera_status == rhs.camera_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator1> & lhs, const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_amr_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d93bc37b6aad1095038c91fe2329616";
  }

  static const char* value(const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d93bc37b6aad109ULL;
  static const uint64_t static_value2 = 0x5038c91fe2329616ULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_amr_service/mechmind_srvResponse";
  }

  static const char* value(const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Response\n"
"\n"
"int32 camera_status\n"
"\n"
;
  }

  static const char* value(const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mechmind_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_amr_service::mechmind_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "camera_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.camera_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_MECHMIND_SRVRESPONSE_H
