// Generated by gencpp from file delta_amr_service/mechmind_srv.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_MECHMIND_SRV_H
#define DELTA_AMR_SERVICE_MESSAGE_MECHMIND_SRV_H

#include <ros/service_traits.h>


#include <delta_amr_service/mechmind_srvRequest.h>
#include <delta_amr_service/mechmind_srvResponse.h>


namespace delta_amr_service
{

struct mechmind_srv
{

typedef mechmind_srvRequest Request;
typedef mechmind_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mechmind_srv
} // namespace delta_amr_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delta_amr_service::mechmind_srv > {
  static const char* value()
  {
    return "7e7b687eeeaf11191ef09103f57fbbe7";
  }

  static const char* value(const ::delta_amr_service::mechmind_srv&) { return value(); }
};

template<>
struct DataType< ::delta_amr_service::mechmind_srv > {
  static const char* value()
  {
    return "delta_amr_service/mechmind_srv";
  }

  static const char* value(const ::delta_amr_service::mechmind_srv&) { return value(); }
};


// service_traits::MD5Sum< ::delta_amr_service::mechmind_srvRequest> should match
// service_traits::MD5Sum< ::delta_amr_service::mechmind_srv >
template<>
struct MD5Sum< ::delta_amr_service::mechmind_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::mechmind_srv >::value();
  }
  static const char* value(const ::delta_amr_service::mechmind_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::mechmind_srvRequest> should match
// service_traits::DataType< ::delta_amr_service::mechmind_srv >
template<>
struct DataType< ::delta_amr_service::mechmind_srvRequest>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::mechmind_srv >::value();
  }
  static const char* value(const ::delta_amr_service::mechmind_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delta_amr_service::mechmind_srvResponse> should match
// service_traits::MD5Sum< ::delta_amr_service::mechmind_srv >
template<>
struct MD5Sum< ::delta_amr_service::mechmind_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::mechmind_srv >::value();
  }
  static const char* value(const ::delta_amr_service::mechmind_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::mechmind_srvResponse> should match
// service_traits::DataType< ::delta_amr_service::mechmind_srv >
template<>
struct DataType< ::delta_amr_service::mechmind_srvResponse>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::mechmind_srv >::value();
  }
  static const char* value(const ::delta_amr_service::mechmind_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_MECHMIND_SRV_H
