// Generated by gencpp from file delta_amr_service/realsense_srvResponse.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_REALSENSE_SRVRESPONSE_H
#define DELTA_AMR_SERVICE_MESSAGE_REALSENSE_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_amr_service
{
template <class ContainerAllocator>
struct realsense_srvResponse_
{
  typedef realsense_srvResponse_<ContainerAllocator> Type;

  realsense_srvResponse_()
    : human_dist(0.0)
    , camera_status_realsense(0)  {
    }
  realsense_srvResponse_(const ContainerAllocator& _alloc)
    : human_dist(0.0)
    , camera_status_realsense(0)  {
  (void)_alloc;
    }



   typedef float _human_dist_type;
  _human_dist_type human_dist;

   typedef int32_t _camera_status_realsense_type;
  _camera_status_realsense_type camera_status_realsense;





  typedef boost::shared_ptr< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct realsense_srvResponse_

typedef ::delta_amr_service::realsense_srvResponse_<std::allocator<void> > realsense_srvResponse;

typedef boost::shared_ptr< ::delta_amr_service::realsense_srvResponse > realsense_srvResponsePtr;
typedef boost::shared_ptr< ::delta_amr_service::realsense_srvResponse const> realsense_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator1> & lhs, const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.human_dist == rhs.human_dist &&
    lhs.camera_status_realsense == rhs.camera_status_realsense;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator1> & lhs, const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_amr_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75fa5ea499c8db0d1f748d91dcfa33bd";
  }

  static const char* value(const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75fa5ea499c8db0dULL;
  static const uint64_t static_value2 = 0x1f748d91dcfa33bdULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_amr_service/realsense_srvResponse";
  }

  static const char* value(const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Response\n"
"\n"
"float32 human_dist\n"
"\n"
"int32 camera_status_realsense\n"
"\n"
;
  }

  static const char* value(const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.human_dist);
      stream.next(m.camera_status_realsense);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct realsense_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_amr_service::realsense_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_amr_service::realsense_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "human_dist: ";
    Printer<float>::stream(s, indent + "  ", v.human_dist);
    s << indent << "camera_status_realsense: ";
    Printer<int32_t>::stream(s, indent + "  ", v.camera_status_realsense);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_REALSENSE_SRVRESPONSE_H
