// Generated by gencpp from file delta_amr_service/realsense_srv.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_REALSENSE_SRV_H
#define DELTA_AMR_SERVICE_MESSAGE_REALSENSE_SRV_H

#include <ros/service_traits.h>


#include <delta_amr_service/realsense_srvRequest.h>
#include <delta_amr_service/realsense_srvResponse.h>


namespace delta_amr_service
{

struct realsense_srv
{

typedef realsense_srvRequest Request;
typedef realsense_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct realsense_srv
} // namespace delta_amr_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delta_amr_service::realsense_srv > {
  static const char* value()
  {
    return "6c4e0ab4251a9095d0cdc3a5578f78f5";
  }

  static const char* value(const ::delta_amr_service::realsense_srv&) { return value(); }
};

template<>
struct DataType< ::delta_amr_service::realsense_srv > {
  static const char* value()
  {
    return "delta_amr_service/realsense_srv";
  }

  static const char* value(const ::delta_amr_service::realsense_srv&) { return value(); }
};


// service_traits::MD5Sum< ::delta_amr_service::realsense_srvRequest> should match
// service_traits::MD5Sum< ::delta_amr_service::realsense_srv >
template<>
struct MD5Sum< ::delta_amr_service::realsense_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::realsense_srv >::value();
  }
  static const char* value(const ::delta_amr_service::realsense_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::realsense_srvRequest> should match
// service_traits::DataType< ::delta_amr_service::realsense_srv >
template<>
struct DataType< ::delta_amr_service::realsense_srvRequest>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::realsense_srv >::value();
  }
  static const char* value(const ::delta_amr_service::realsense_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delta_amr_service::realsense_srvResponse> should match
// service_traits::MD5Sum< ::delta_amr_service::realsense_srv >
template<>
struct MD5Sum< ::delta_amr_service::realsense_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::realsense_srv >::value();
  }
  static const char* value(const ::delta_amr_service::realsense_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::realsense_srvResponse> should match
// service_traits::DataType< ::delta_amr_service::realsense_srv >
template<>
struct DataType< ::delta_amr_service::realsense_srvResponse>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::realsense_srv >::value();
  }
  static const char* value(const ::delta_amr_service::realsense_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_REALSENSE_SRV_H
