// Generated by gencpp from file delta_amr_service/robot_control_srvRequest.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_ROBOT_CONTROL_SRVREQUEST_H
#define DELTA_AMR_SERVICE_MESSAGE_ROBOT_CONTROL_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_amr_service
{
template <class ContainerAllocator>
struct robot_control_srvRequest_
{
  typedef robot_control_srvRequest_<ContainerAllocator> Type;

  robot_control_srvRequest_()
    : robot_mov_type()
    , robot_mov_point()
    , robot_mov_speed(0.0)  {
    }
  robot_control_srvRequest_(const ContainerAllocator& _alloc)
    : robot_mov_type(_alloc)
    , robot_mov_point(_alloc)
    , robot_mov_speed(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_mov_type_type;
  _robot_mov_type_type robot_mov_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_mov_point_type;
  _robot_mov_point_type robot_mov_point;

   typedef float _robot_mov_speed_type;
  _robot_mov_speed_type robot_mov_speed;





  typedef boost::shared_ptr< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_control_srvRequest_

typedef ::delta_amr_service::robot_control_srvRequest_<std::allocator<void> > robot_control_srvRequest;

typedef boost::shared_ptr< ::delta_amr_service::robot_control_srvRequest > robot_control_srvRequestPtr;
typedef boost::shared_ptr< ::delta_amr_service::robot_control_srvRequest const> robot_control_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator1> & lhs, const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_mov_type == rhs.robot_mov_type &&
    lhs.robot_mov_point == rhs.robot_mov_point &&
    lhs.robot_mov_speed == rhs.robot_mov_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator1> & lhs, const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_amr_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a122c484e7bbcdd0759055620a95c6f0";
  }

  static const char* value(const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa122c484e7bbcdd0ULL;
  static const uint64_t static_value2 = 0x759055620a95c6f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_amr_service/robot_control_srvRequest";
  }

  static const char* value(const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Delta_AMR_Service.srv\n"
"# Request\n"
"\n"
"string robot_mov_type \n"
"string robot_mov_point\n"
"float32 robot_mov_speed\n"
"\n"
;
  }

  static const char* value(const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_mov_type);
      stream.next(m.robot_mov_point);
      stream.next(m.robot_mov_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_control_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_amr_service::robot_control_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_mov_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_mov_type);
    s << indent << "robot_mov_point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_mov_point);
    s << indent << "robot_mov_speed: ";
    Printer<float>::stream(s, indent + "  ", v.robot_mov_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_ROBOT_CONTROL_SRVREQUEST_H
