// Generated by gencpp from file delta_amr_service/robot_control_srv.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_ROBOT_CONTROL_SRV_H
#define DELTA_AMR_SERVICE_MESSAGE_ROBOT_CONTROL_SRV_H

#include <ros/service_traits.h>


#include <delta_amr_service/robot_control_srvRequest.h>
#include <delta_amr_service/robot_control_srvResponse.h>


namespace delta_amr_service
{

struct robot_control_srv
{

typedef robot_control_srvRequest Request;
typedef robot_control_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_control_srv
} // namespace delta_amr_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delta_amr_service::robot_control_srv > {
  static const char* value()
  {
    return "d80efec2e3530caab86fefe684a2fdc0";
  }

  static const char* value(const ::delta_amr_service::robot_control_srv&) { return value(); }
};

template<>
struct DataType< ::delta_amr_service::robot_control_srv > {
  static const char* value()
  {
    return "delta_amr_service/robot_control_srv";
  }

  static const char* value(const ::delta_amr_service::robot_control_srv&) { return value(); }
};


// service_traits::MD5Sum< ::delta_amr_service::robot_control_srvRequest> should match
// service_traits::MD5Sum< ::delta_amr_service::robot_control_srv >
template<>
struct MD5Sum< ::delta_amr_service::robot_control_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::robot_control_srv >::value();
  }
  static const char* value(const ::delta_amr_service::robot_control_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::robot_control_srvRequest> should match
// service_traits::DataType< ::delta_amr_service::robot_control_srv >
template<>
struct DataType< ::delta_amr_service::robot_control_srvRequest>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::robot_control_srv >::value();
  }
  static const char* value(const ::delta_amr_service::robot_control_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delta_amr_service::robot_control_srvResponse> should match
// service_traits::MD5Sum< ::delta_amr_service::robot_control_srv >
template<>
struct MD5Sum< ::delta_amr_service::robot_control_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::robot_control_srv >::value();
  }
  static const char* value(const ::delta_amr_service::robot_control_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::robot_control_srvResponse> should match
// service_traits::DataType< ::delta_amr_service::robot_control_srv >
template<>
struct DataType< ::delta_amr_service::robot_control_srvResponse>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::robot_control_srv >::value();
  }
  static const char* value(const ::delta_amr_service::robot_control_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_ROBOT_CONTROL_SRV_H
