// Generated by gencpp from file delta_amr_service/upload_srvRequest.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_UPLOAD_SRVREQUEST_H
#define DELTA_AMR_SERVICE_MESSAGE_UPLOAD_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_amr_service
{
template <class ContainerAllocator>
struct upload_srvRequest_
{
  typedef upload_srvRequest_<ContainerAllocator> Type;

  upload_srvRequest_()
    : upload_cmd()  {
    }
  upload_srvRequest_(const ContainerAllocator& _alloc)
    : upload_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _upload_cmd_type;
  _upload_cmd_type upload_cmd;





  typedef boost::shared_ptr< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct upload_srvRequest_

typedef ::delta_amr_service::upload_srvRequest_<std::allocator<void> > upload_srvRequest;

typedef boost::shared_ptr< ::delta_amr_service::upload_srvRequest > upload_srvRequestPtr;
typedef boost::shared_ptr< ::delta_amr_service::upload_srvRequest const> upload_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_amr_service::upload_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_amr_service::upload_srvRequest_<ContainerAllocator1> & lhs, const ::delta_amr_service::upload_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.upload_cmd == rhs.upload_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_amr_service::upload_srvRequest_<ContainerAllocator1> & lhs, const ::delta_amr_service::upload_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_amr_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c1c533946e4ad554fe5ef8f8b3a59d6";
  }

  static const char* value(const ::delta_amr_service::upload_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c1c533946e4ad55ULL;
  static const uint64_t static_value2 = 0x4fe5ef8f8b3a59d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_amr_service/upload_srvRequest";
  }

  static const char* value(const ::delta_amr_service::upload_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Delta_AMR_Service.srv\n"
"# Request\n"
"\n"
"string upload_cmd\n"
"\n"
;
  }

  static const char* value(const ::delta_amr_service::upload_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.upload_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct upload_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_amr_service::upload_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_amr_service::upload_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "upload_cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.upload_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_UPLOAD_SRVREQUEST_H
