// Generated by gencpp from file delta_amr_service/upload_srv.msg
// DO NOT EDIT!


#ifndef DELTA_AMR_SERVICE_MESSAGE_UPLOAD_SRV_H
#define DELTA_AMR_SERVICE_MESSAGE_UPLOAD_SRV_H

#include <ros/service_traits.h>


#include <delta_amr_service/upload_srvRequest.h>
#include <delta_amr_service/upload_srvResponse.h>


namespace delta_amr_service
{

struct upload_srv
{

typedef upload_srvRequest Request;
typedef upload_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct upload_srv
} // namespace delta_amr_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delta_amr_service::upload_srv > {
  static const char* value()
  {
    return "9509961624cae8e89290906327b798e8";
  }

  static const char* value(const ::delta_amr_service::upload_srv&) { return value(); }
};

template<>
struct DataType< ::delta_amr_service::upload_srv > {
  static const char* value()
  {
    return "delta_amr_service/upload_srv";
  }

  static const char* value(const ::delta_amr_service::upload_srv&) { return value(); }
};


// service_traits::MD5Sum< ::delta_amr_service::upload_srvRequest> should match
// service_traits::MD5Sum< ::delta_amr_service::upload_srv >
template<>
struct MD5Sum< ::delta_amr_service::upload_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::upload_srv >::value();
  }
  static const char* value(const ::delta_amr_service::upload_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::upload_srvRequest> should match
// service_traits::DataType< ::delta_amr_service::upload_srv >
template<>
struct DataType< ::delta_amr_service::upload_srvRequest>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::upload_srv >::value();
  }
  static const char* value(const ::delta_amr_service::upload_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delta_amr_service::upload_srvResponse> should match
// service_traits::MD5Sum< ::delta_amr_service::upload_srv >
template<>
struct MD5Sum< ::delta_amr_service::upload_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delta_amr_service::upload_srv >::value();
  }
  static const char* value(const ::delta_amr_service::upload_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_amr_service::upload_srvResponse> should match
// service_traits::DataType< ::delta_amr_service::upload_srv >
template<>
struct DataType< ::delta_amr_service::upload_srvResponse>
{
  static const char* value()
  {
    return DataType< ::delta_amr_service::upload_srv >::value();
  }
  static const char* value(const ::delta_amr_service::upload_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELTA_AMR_SERVICE_MESSAGE_UPLOAD_SRV_H
