(cl:in-package motor_feedback_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSITIONL-VAL
          POSITIONL
          POSITIONR-VAL
          POSITIONR
          AVELOCITYL-VAL
          AVELOCITYL
          AVELOCITYR-VAL
          AVELOCITYR
          DVELOCITYL-VAL
          DVELOCITYL
          DVELOCITYR-VAL
          DVELOCITYR
          AVELOCITYL_LPF-VAL
          AVELOCITYL_LPF
          AVELOCITYL_M-VAL
          AVELOCITYL_M
          AVELOCITYR_LPF-VAL
          AVELOCITYR_LPF
          AVELOCITYR_M-VAL
          AVELOCITYR_M
          VX-VAL
          VX
          VY-VAL
          VY
          VTH-VAL
          VTH
          DELTA_X-VAL
          DELTA_X
          DELTA_Y-VAL
          DELTA_Y
          DELTA_TH-VAL
          DELTA_TH
          X-VAL
          X
          Y-VAL
          Y
          TH-VAL
          TH
))